localRepositories:   
  kaizoku-dev-grdl-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  kaizoku-rc-grdl-local:
    type: gradle
    repoLayout: maven-2-default 
    xray:   
      enabled: true
  kaizoku-dev-docker-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaizoku-rc-docker-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaizoku-release-docker-local:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    xray:   
      enabled: true
  kaivengers-dev-helm-local:
    type: helm
    repoLayout: simple-default 
    xray:   
      enabled: false
remoteRepositories: 
  kaizoku-jcenter-grdl-remote:
    type: gradle 
    repoLayout: maven-2-default 
    url: https://jcenter.bintray.com 
    xray:   
      enabled: true
  kaizoku-dockerhub-remote:
    type: docker 
    url: https://registry-1.docker.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  kaizoku-bintray-remote:
    type: docker
    url: https://docker.bintray.io/
    dockerApiVersion: V2
    repoLayout: simple-default 
    enableTokenAuthentication: true
    xray:   
      enabled: true
  kaivengers-chartcenter-remote:
    type: helm
    url: https://repo.chartcenter.io/
    repoLayout: simple-default 
    xray:   
      enabled: false
virtualRepositories: 
  kaizoku-docker:
    type: docker
    dockerApiVersion: V2
    repoLayout: simple-default 
    repositories:   
      - kaizoku-dev-docker-local
      - kaizoku-rc-docker-local
      - kaizoku-release-docker-local
      - kaizoku-dockerhub-remote
      - kaizoku-bintray-remote
    defaultDeploymentRepo: kaizoku-dev-docker-local
  kaizoku-grdl:
    type: gradle
    repoLayout: maven-2-default 
    repositories:   
      - kaizoku-dev-grdl-local
      - kaizoku-rc-grdl-local
      - kaizoku-jcenter-grdl-remote
      - kaivengers-release-docker-local
    defaultDeploymentRepo: kaizoku-dev-grdl-local