pipelines:
  - name: k8s_project_init
    configuration:
      environmentVariables:
        readOnly:
          envVarDockerRegistry: kaivengers-docker.artifactory-eu-yannc3-0.soleng-emea-staging.jfrog.team:80
          envVarDockerPushRepo: kaivengers-docker
          envVarDockerImageName: jfrog/pipelines-u18node
          envVarBaseImageTag: 10.21.0-jfrog
          envVarHelmRepo: kaivengers-helm
          envVarHelmName: myapp
          envVarHelmVers: 1.0.0
    steps:
      - name: create_resources
        type: Bash
        configuration:
          affinityGroup: helm
          runtime:
            type: host
          inputResources:
            - name: src_code_k8s_app
          integrations:
            - name: artifactory_eu
        execution:
          onExecute:
            - cd ${res_src_code_k8s_app_resourcePath}/chart/CI/jfrog
            - ls -l && chmod +x init.sh
            - ./init.sh -u  ${int_artifactory_eu_url/%artifactory/} -p ${int_artifactory_eu_apikey}
          onStart:
            - sudo mkdir -p /etc/docker 
            - > 
              sudo jq -n  "{\"insecure-registries\": [\"${envVarDockerRegistry}\"]}" > /etc/docker/daemon.json
            - sudo systemctl restart docker
            - sudo cat /etc/docker/daemon.json


      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          affinityGroup: helm
          helmVersion: 3
          chartPath: chart/content/
          lint: true
          autoPublishBuildInfo: true
          inputResources:
            - name: src_code_k8s_helm
          inputSteps:
            - name: create_resources
          integrations:
            - name: artifactory_eu
          outputResources:
            - name: hc_my_app
            - name: bi_hc_my_app
        execution:
          onStart:
            - curl  https://get.helm.sh/helm-canary-linux-amd64.tar.gz | tar xvz -C /tmp
            - mv /tmp/linux-amd64/helm /usr/local/bin/helm3
            - helm3 version
            - cat ${res_src_code_k8s_helm_resourcePath}/chart/CI/jfrog/Dockerfile

# WORKAROUND FOR HELM DEPLOY WHICH REQUIRES A NEWER JFROG CLI VERSION   
      - name: build_helm_base_image
        type: DockerBuild
        configuration:
          affinityGroup: helm
          dockerFileName: Dockerfile
          dockerFileLocation: chart/CI/jfrog/
          dockerImageName: ${envVarDockerRegistry}/${envVarDockerImageName}
          dockerImageTag: ${envVarBaseImageTag}
          inputSteps:
            - name: publish_helm_chart
          inputResources:
            - name: src_dockerfile_base_image_helm
          integrations:
            - name: artifactory_eu

      - name: publish_helm_base_image
        type: DockerPush
        configuration:
          affinityGroup: helm
          targetRepository: ${envVarDockerPushRepo}
          autoPublishBuildInfo: true
          forceXrayScan: true
          inputSteps:
            - name: build_helm_base_image
          integrations:
            - name: artifactory_eu
          outputResources:
            - name: bi_base_image_helm

